### ISSUE TITLE
Thermal electric water use

### ISSUE THREAD

**Issue by hwreeves-USGS** [aleaf/usgs-map-gwmodels#10]
The script to pre-process thermal-electric GW use (te_wateruse.py) shares a lot of code with swuds.py:

I propose to add methods and attributes to the Swuds class to process the TE - seems like the major
additions are specifying the default columns for 2010 and 2015 (they differ in the script), and updating
the monthly processing to use the plant_code.  I don't think its worth making a separate TE class that
inherits from the Swuds class; but once this is set up it can be re-factored if that is desired by 
the team.  HWR

**Comment by aleaf** [comment]
@hwreeves-USGS sounds good. Would it make sense to rename the Swuds class to something more general, or is the TE data kind of a subset of Swuds? I don't know enough about water use...

**Comment by hwreeves-USGS** [comment]
TE is a subset of Swuds(), its looking like I should inherit the swuds class -
oh well, hopefully its not hard for others to follow.

HWR


Howard W. Reeves
Groundwater and Watershed Modeling Team Lead
USGS Upper Midwest Water Science Center
5840 Enterprise Drive
Lansing, Michigan 48911
517-887-8914
________________________________
